services:
  app:
    build:
      dockerfile: ./Dockerfile
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    environment:
      - CARGO_TARGET_DIR=/target
      - TZ=Europe/Stockholm
    volumes:
      - .:/app
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: local
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33006:3306

  adminer:
      image: adminer
      restart: always
      ports:
        - 9000:8080

  nginx:
    image: nginx:alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

volumes:
  db_data: